<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gitlab" nsURI="ecore://nasdanika.org/models/gitlab" nsPrefix="org.nasdanika.models.gitlab">
  <eClassifiers xsi:type="ecore:EClass" name="Loadable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timestamp when this object was loded excluding contents, which might be loaded separately. Deprecated, use loads"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loads" upperBound="-1"
        eType="#//Load" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Load">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Provides information about data load"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Source system. E.g. URL or user account and URL"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference name, e.g. branches. The containing object (self) if empty."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load start"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Load end"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Error if load failed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of elements loaded"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GitLab" eSuperTypes="#//Loadable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a GitLab host/instance. The root of the GitLab model."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//AbstractGroup" containment="true" eKeys="#//AbstractGroup/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//Principal" containment="true" eKeys="#//Principal/id"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topLevelGroupsLoaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timestamp when the top level groups were loaded. Deprecated, use loads"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractGroup" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//Loadable #//AbstractGroup">
    <eOperations name="createReference" eType="#//GroupReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avatarUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lfsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//AbstractProject" containment="true" eKeys="#//AbstractProject/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shares" upperBound="-1"
        eType="#//ProjectSharedGroup" eOpposite="#//ProjectSharedGroup/group"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositorySize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lfsObjectsSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobArtifactsSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subGroups" upperBound="-1"
        eType="#//AbstractGroup" containment="true" eKeys="#//AbstractGroup/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Member" containment="true" eKeys="#//Principal/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeOwnership" upperBound="-1"
        eType="#//codeowners/CodeOwner" eOpposite="#//codeowners/CodeOwner/group"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subGroupsLoaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timestamp when this group's sub-groups were loaded. Deprecated, use loads"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectsLoaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timestamp when this group projects were loaded. Deprecated use loads"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupReference">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//Reference">
      <eTypeArguments eClassifier="#//Group"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//AbstractGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Principal" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractUser" abstract="true" eSuperTypes="#//Loadable #//Principal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avatarUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eMail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member" eSuperTypes="#//AbstractUser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User" eOpposite="#//User/membership"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessLevel" eType="#//AccessLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expiresAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserReference">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//Reference">
      <eTypeArguments eClassifier="#//User"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Principal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//AbstractUser">
    <eOperations name="createReference" eType="#//UserReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//AbstractProject" containment="true" eKeys="#//AbstractProject/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="membership" upperBound="-1"
        eType="#//Member" eOpposite="#//Member/user"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" upperBound="-1" eType="#//Owner"
        eOpposite="#//Owner/user"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdProjects" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/creator" eKeys="#//AbstractProject/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributions" upperBound="-1"
        eType="#//Contributor" eOpposite="#//Contributor/user"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeOwnership" upperBound="-1"
        eType="#//codeowners/CodeOwner" eOpposite="#//codeowners/CodeOwner/user"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProject" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//Loadable #//AbstractProject">
    <eOperations name="createReference" eType="#//ProjectReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="approvalsBeforeMerge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="archived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avatarUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerRegistryEnabled"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creatorId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creator" eType="#//User"
        eOpposite="#//User/createdProjects"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultBranch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forksCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forkedFromId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forkedFrom" eType="#//Project"
        eOpposite="#//Project/forks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forks" upperBound="-1"
        eType="#//Project" eOpposite="#//Project/forkedFrom" eKeys="#//AbstractProject/id"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpUrlToRepo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPublic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="issuesEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastsActivityAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lfsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergeMethod" eType="#//MergeMethod"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergeRequestsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameWithNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyAllowMergeIfPipelineSucceeds"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowMergeOnSkippedPipeline"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyAllowMergeIfAllDiscussionsAreResolved"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openIssuesCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Owner"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pathWithNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectAccess" eType="#//ProjectAccess"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupAccess" eType="#//ProjectAccess"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicJobs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedWithGroups" upperBound="-1"
        eType="#//ProjectSharedGroup" containment="true" eKeys="#//ProjectSharedGroup/id"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositoryStorage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestAccessEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runnersToken" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sharedRunnersEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="snippetsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshUrlToRepo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="starCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibilityLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wallEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wikiEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="printingMergeRequestLinkEnabled"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolveOutdatedDiffDiscussions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statistics" eType="#//ProjectStatistics"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initializeWithReadme" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packagesEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emptyRepo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licenseUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="license" eType="#//ProjectLicense"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customAttributes" upperBound="-1"
        eType="#//CustomAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildCoverageRegex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildGitStrategy" eType="#//BuildGitStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readmeUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canCreateMergeRequestIn"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importStatus" eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ciDefaultGitDepth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ciForwardDeploymentEnabled"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ciConfigPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="removeSourceBranchAfterMerge"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoDevopsEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoDevopsDeployStrategy"
        eType="#//AutoDevopsDeployStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autocloseReferencedIssues"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailsDisabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suggestionCommitMessage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="squashOption" eType="#//SquashOption"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
        eType="#//Branch" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//TreeItem/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributors" upperBound="-1"
        eType="#//Contributor" containment="true" eKeys="#//Principal/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Member" containment="true" eKeys="#//Principal/id"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branchesLoaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timestamp when this project's branches were loaded. Deprecated, use loads"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branchesLoadError" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Branches load error. Deprecated, use loads"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commits" upperBound="-1"
        eType="#//Commit" containment="true" eKeys="#//Commit/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pipelines" upperBound="-1"
        eType="#//pipeline/Pipeline" containment="true" eKeys="#//pipeline/Pipeline/id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectReference">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//Reference">
      <eTypeArguments eClassifier="#//Project"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//AbstractProject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectSharedGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessLevel" eType="#//AccessLevel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//Group"
        eOpposite="#//Group/shares"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectStatistics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commitCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositorySize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wikiSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lfsObjectsSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobArtifactsSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packagesSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectLicense">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="htmlUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="Public"/>
    <eLiterals name="Private" value="1"/>
    <eLiterals name="Internal" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessLevel">
    <eLiterals name="Invalid" value="-1"/>
    <eLiterals name="None"/>
    <eLiterals name="MinimalAccess" value="5"/>
    <eLiterals name="Guest" value="10"/>
    <eLiterals name="Reporter" value="20"/>
    <eLiterals name="Developer" value="30"/>
    <eLiterals name="Maintainer" value="40"/>
    <eLiterals name="Owner" value="50"/>
    <eLiterals name="Admin" value="60"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contributor" eSuperTypes="#//AbstractUser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User" eOpposite="#//User/contributions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A reference to a matching user "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commitCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deletions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commits" upperBound="-1"
        eType="#//Commit" eOpposite="#//Commit/contributor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributor" eType="#//Contributor"
        eOpposite="#//Contributor/commits"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentIds" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
        eType="#//Commit" eOpposite="#//Commit/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Commit" eOpposite="#//Commit/parents"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authoredDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorEmail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="committedDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="committerEmail" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="committerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
        eType="#//Branch" eOpposite="#//Branch/commit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MergeMethod">
    <eLiterals name="Merge"/>
    <eLiterals name="RebaseMerge" value="1"/>
    <eLiterals name="FastForward" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectAccess">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessLevel" eType="#//AccessLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notificationLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomAttribute" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuildGitStrategy">
    <eLiterals name="Fetch"/>
    <eLiterals name="Clone" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="Info" literal="Info"/>
    <eLiterals name="Success" value="1"/>
    <eLiterals name="Warning" value="2"/>
    <eLiterals name="Error" value="3"/>
    <eLiterals name="Fail" value="4"/>
    <eLiterals name="Cancel" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AutoDevopsDeployStrategy">
    <eLiterals name="Continuous" literal="Info"/>
    <eLiterals name="Manual" value="1"/>
    <eLiterals name="TimedIncremental" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SquashOption">
    <eLiterals name="Never" literal="Info"/>
    <eLiterals name="Always" value="1"/>
    <eLiterals name="DefaultOn" value="2"/>
    <eLiterals name="DefaultOff" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Owner" eSuperTypes="#//AbstractUser">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User" eOpposite="#//User/owns">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A reference to a matching user "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeItem" eSuperTypes="#//Loadable ../../org.nasdanika.ncore/model/ncore.ecore#//TreeItem">
    <eOperations name="createReference" eType="#//TreeItemReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeItemReference">
    <eGenericSuperTypes eClassifier="#//TreeItem"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//Reference">
      <eTypeArguments eClassifier="#//TreeItem"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tree" eSuperTypes="#//TreeItem ../../org.nasdanika.ncore/model/ncore.ecore#//Tree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="treeItemsLoaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Timestamp when this tree's items were loaded"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="#//Tree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="developersCanMerge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="developersCanPush" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="merged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isProtected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canPush" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commit" eType="#//Commit"
        eOpposite="#//Commit/branches"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Blob" eSuperTypes="#//TreeItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryFile" eSuperTypes="#//Blob">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Base class for repository files with different types of content"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commitId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastCommitId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextRepositoryFile" eSuperTypes="#//RepositoryFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryRepositoryFile" eSuperTypes="#//RepositoryFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectRepositoryFile" eSuperTypes="#//RepositoryFile">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A repository file with content loaded as EObject. For example, Maven pom.xml file can be loaded as an object representing the file structure."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListRepositoryFile" eSuperTypes="#//RepositoryFile">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Repository file which content gets decoded to a list of objects, e.g. a list of properties - key/value pairs"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eSubpackages name="codeowners" nsURI="ecore://nasdanika.org/models/gitlab/codeowners"
      nsPrefix="org.nasdanika.models.gitlab.codeowners">
    <eClassifiers xsi:type="ecore:EClass" name="CodeOwner">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"
          eOpposite="#//User/codeOwnership"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//Group"
          eOpposite="#//Group/codeOwnership"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codeOwners" upperBound="-1"
          eType="#//codeowners/CodeOwner" containment="true" eKeys="#//codeowners/CodeOwner/id"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DefaultSection" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="approvers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="codeOwners" upperBound="-1"
          eType="#//codeowners/CodeOwner" containment="true" eKeys="#//codeowners/CodeOwner/id"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
          eType="#//codeowners/Entry" containment="true" eKeys="#//codeowners/Entry/pattern"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//codeowners/DefaultSection">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CodeOwners" eSuperTypes="#//RepositoryFile #//codeowners/DefaultSection">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
          eType="#//codeowners/Section" containment="true" eKeys="#//codeowners/Section/name"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="pipeline" nsURI="ecore://nasdanika.org/models/gitlab/pipeline"
      nsPrefix="org.nasdanika.models.gitlab.pipeline">
    <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
      <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" upperBound="-1"
          eType="#//pipeline/Job" containment="true" eKeys="#//pipeline/Job/id"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//pipeline/PipelineStatus"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="beforeSha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="yamlErrors" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="updatedAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startedAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="finishedAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="committedAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="queuedDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="webUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="detailedStatus" eType="#//pipeline/DetailedStatus"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Job">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="commit" eType="#//Commit"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="createdAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="finishedAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="erasedAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactsExpireAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="runner" eType="#//pipeline/Runner"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startedAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifactsFile" eType="#//pipeline/ArtifactsFile"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
          eType="#//pipeline/Artifact" containment="true" eKeys="#//pipeline/Artifact/fileName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="webUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobStatus" eType="#//pipeline/JobStatus"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="manual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowFailure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="queuedDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PipelineStatus">
      <eLiterals name="CREATED"/>
      <eLiterals name="WAITING_FOR_RESOURCE" value="1"/>
      <eLiterals name="PREPARING" value="2"/>
      <eLiterals name="PENDING" value="3"/>
      <eLiterals name="RUNNING" value="4"/>
      <eLiterals name="SUCCESS" value="5"/>
      <eLiterals name="FAILED" value="6"/>
      <eLiterals name="CANCELED" value="7"/>
      <eLiterals name="SKIPPED" value="8"/>
      <eLiterals name="MANUAL" value="9"/>
      <eLiterals name="SCHEDULED" value="10"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DetailedStatus"/>
    <eClassifiers xsi:type="ecore:EClass" name="ArtifactsFile">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coverage" eType="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//ModuleCoverage"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Artifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileType" eType="#//pipeline/FileType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Runner"/>
    <eClassifiers xsi:type="ecore:EEnum" name="JobStatus">
      <eLiterals name="CREATED"/>
      <eLiterals name="RUNNING" value="1"/>
      <eLiterals name="PENDING" value="2"/>
      <eLiterals name="SUCCESS" value="3"/>
      <eLiterals name="FAILED" value="4"/>
      <eLiterals name="CANCELED" value="5"/>
      <eLiterals name="SKIPPED" value="6"/>
      <eLiterals name="MANUAL" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FileType">
      <eLiterals name="ARCHIVE"/>
      <eLiterals name="METADATA" value="1"/>
      <eLiterals name="TRACE" value="2"/>
      <eLiterals name="JUNIT" value="3"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
